// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4yfdQBR4oJTPiW4Qi3TvkGygbJPx0-lU',
    appId: '1:207089202704:android:87a14503713f1ea8523c95',
    messagingSenderId: '207089202704',
    projectId: 'aiguruji-9f371',
    storageBucket: 'aiguruji-9f371.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqcpW1QTUissop6LTr6WqmhzkEjkIHAd8',
    appId: '1:207089202704:ios:d0b3823024f9f7c2523c95',
    messagingSenderId: '207089202704',
    projectId: 'aiguruji-9f371',
    storageBucket: 'aiguruji-9f371.firebasestorage.app',
    androidClientId: '207089202704-8ro7mmrpcd1952mk6s6lfbksv9hlht3s.apps.googleusercontent.com',
    iosClientId: '207089202704-ete6udaabg2ggl1janljrh0d3ibmn5c0.apps.googleusercontent.com',
    iosBundleId: 'com.xcoder.aiguruji',
  );

}